### PR TITLE
Updated 23 Feb

### PR DESCRIPTION
**Pull request by Harshpatel44**
1.More Efficient
2.GUI Included
3.Next Link Feature Included
4.Comparatively More Fast
#No need of Logfile 
Run user2.py

### CODE REVIEW

**Comment by mistryvatsal** [comment]
@Harshpatel44 : Good one pal. Append your code to the original files. i.e to the HTMLScrapping.py and User.py also for GUI make another module for clarity in designing of this bot. Codes are really nice. I appreciate your contribution. Have a look on pycache folder, avoid codes making compiling cache files.

**Comment by mistryvatsal** [comment]
@Harshpatel44 : Append the codes to the initial files and then pull a request . I will merge it.

**Comment by Harshpatel44** [comment]
I should Replace it or append it ??

**Comment by mistryvatsal** [comment]
@Harshpatel44 : append the explicit codes by you, keep your codes in functions and structure internal calling of all.

**Comment by Harshpatel44** [comment]
Done.

**Comment by mistryvatsal** [comment]
@Harshpatel44 . Good to go. Good work buddy.

**Comment by Harshpatel44** [comment]
Yeah Thanks.

**Pull request merged**
